### ISSUE TITLE
Run individual game (keyError)

### ISSUE THREAD

**Issue by jbwilkes** [LukasErekson/pyrisk#14]
based upon current code in the repo

[jbwilkes@byu.local@acme39 pyrisk]$ time python pyrisk.py --nocurses StupidAI BetterAI --deal
Traceback (most recent call last):
  File "pyrisk.py", line 139, in <module>
    wrapper(None, **kwargs)
  File "pyrisk.py", line 18, in wrapper
    g = Game(screen=stdscr, **kwargs)
  File "/acmeshare/jbwilkes/402_projects/pyrisk/game.py", line 31, in __init__
    self.logger = options['logger']
KeyError: 'logger'

real	0m0.065s
user	0m0.040s
sys	0m0.008s

**Comment by jbwilkes** [comment]
I didn't get this issue when I add the `-g` parameter

**Comment by lodeous** [comment]
It looks like the issue comes from here. If the games are 1 we jump straight into the wrapper instead of the launch_in_process code, which creates a logger to pass in. It won't even work with curses turned on. I think I will need to create a logger for the path with 1 game too. When there is one game it bypasses parallel processing because its pointless.
```
if args.games == 1:
        if args.curses:
            import curses
            curses.wrapper(wrapper, **kwargs)
        else:
            wrapper(None, **kwargs)
    else:
        if args.processes > 1:
            execute_in_parallel(args, **kwargs)
        else:
            launch_in_process(0, args.games, args, **kwargs)
```
